name: ChatReward
main: Palente\ChatReward\ChatReward
api: [3.0.0]
author: Palente
version: 1.0.5
description: "Get rewarded by talking!"
website: https://github.com/Palente
softdepend:
  - EconomyAPI
  - PurePerms
commands:
  chatreward:
    usage: "/chatreward <info> [player]"
    description: "ChatReward command"
    aliases: ["cr"]
    permission: chatreward.command.chatreward
permissions:
  chatreward.*:
    description: ""
    children:
      chatreward.command.*:
        description: ""
        children:
          chatreward.command.chatreward:
            description: ""
            default: true